import { useMemo, useState } from 'react';
import { NavLink, Route, Routes } from 'react-router-dom';
import { LayoutDashboard, ClipboardPlus, Factory, History, BarChart3, Database, Users, Settings, Menu, Search, Plus, FileDown, Upload, Pencil, ChevronDown } from 'lucide-react';
import * as XLSX from 'xlsx';

type MasterName='Parties'|'Beams'|'Shades'|'Sizes';
type Design={id:number;name:string;beam:string;shade:string;size:string;threads:string[]};
type Program={id:number;loom:number;party:string;po:string;poDate:string;productionDate:string;design:string;beam:string;shade:string;threads:string[];pick:number;meters:number;articles:number};
const seed={Parties:['ABC Furnishings','Classic Décor'],Beams:['Beam 01','Beam 02'],Shades:['Ivory','Beige'],Sizes:['60 inch','72 inch']};
const seedDesigns:Design[]=[{id:1,name:'D-101',beam:'Beam 01',shade:'Ivory',size:'60 inch',threads:['Warp White','Gold Texture','Ivory Fill']}];

function Shell(){const[open,setOpen]=useState(true);return <div className="app"><aside className={open?'sidebar':'sidebar collapsed'}><div className="brand"><div className="brandmark">VF</div>{open&&<div><b>VINEET</b><span>FURNISHINGS ERP</span></div>}</div><nav>{[
['/','Dashboard',LayoutDashboard],['/loom-program','Loom Program',ClipboardPlus],['/production','Production Entry',Factory],['/history','Production History',History],['/analytics','Analytics',BarChart3],['/masters','Master Data',Database],['/users','Users',Users],['/settings','Settings',Settings]
].map(([to,label,Icon]:any)=><NavLink key={to} to={to} end={to==='/'}><Icon size={20}/>{open&&<span>{label}</span>}</NavLink>)}</nav></aside><main><header><button className="iconbtn" onClick={()=>setOpen(!open)}><Menu/></button><div className="search"><Search size={18}/><input placeholder="Search ERP..."/></div><div className="user">AC</div></header><section className="page"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/loom-program" element={<LoomProgram/>}/><Route path="/production" element={<Placeholder title="Production Entry"/>}/><Route path="/history" element={<HistoryPage/>}/><Route path="/analytics" element={<Analytics/>}/><Route path="/masters" element={<Masters/>}/><Route path="/users" element={<Placeholder title="User Management"/>}/><Route path="/settings" element={<Placeholder title="Settings"/>}/></Routes></section></main></div>}
function Title({title,subtitle,action}:{title:string;subtitle:string;action?:any}){return <div className="title"><div><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function Dashboard(){const cards=[['Today’s Meters','1,284 m','+8.4%'],['Today’s Articles','426','+12.1%'],['Running Looms','38 / 52','73% active'],['Pending Programs','14','Needs attention']];return <><Title title="Production Dashboard" subtitle="Live overview of loom programs and factory output" action={<button className="primary"><Plus size={18}/>New Loom Program</button>}/><div className="cards">{cards.map(c=><div className="card" key={c[0]}><span>{c[0]}</span><strong>{c[1]}</strong><small>{c[2]}</small></div>)}</div><div className="grid2"><div className="panel"><h3>Production Overview</h3><div className="bars">{[64,82,70,92,76,88,61].map((v,i)=><div key={i}><span style={{height:`${v}%`}}></span><small>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</small></div>)}</div></div><div className="panel"><h3>Loom Status</h3><div className="donut"><div><b>73%</b><span>Running</span></div></div><div className="legend"><span>38 Running</span><span>8 Idle</span><span>6 Maintenance</span></div></div></div></>}
function Masters(){const[data,setData]=useState(seed);const[designs,setDesigns]=useState(seedDesigns);const[active,setActive]=useState<MasterName|'Designs'>('Designs');const[query,setQuery]=useState('');const add=()=>{const name=prompt(`Enter new ${active.slice(0,-1)} name`);if(!name)return;if(active==='Designs')setDesigns([...designs,{id:Date.now(),name,beam:data.Beams[0]||'',shade:data.Shades[0]||'',size:data.Sizes[0]||'',threads:[]}]);else setData({...data,[active]:[...data[active],name]});};const exportExcel=()=>{const rows=active==='Designs'?designs.map(d=>({...d,threads:d.threads.join(', ')})):data[active].map(name=>({name}));const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,active);XLSX.writeFile(wb,`${active.toLowerCase()}-master.xlsx`)};const filtered=active==='Designs'?designs.filter(x=>x.name.toLowerCase().includes(query.toLowerCase())):data[active].filter(x=>x.toLowerCase().includes(query.toLowerCase()));return <><Title title="Master Data" subtitle="Manage reusable factory information" action={<div className="actions"><button onClick={exportExcel}><FileDown size={17}/>Export Excel</button><button><Upload size={17}/>Import</button><button className="primary" onClick={add}><Plus size={17}/>Add New</button></div>}/><div className="master-tabs">{(['Designs','Parties','Beams','Shades','Sizes'] as const).map(x=><button className={active===x?'active':''} onClick={()=>setActive(x)} key={x}>{x}</button>)}</div><div className="panel"><div className="tabletools"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${active.toLowerCase()}...`}/></div><button>Filters <ChevronDown size={16}/></button></div><table><thead><tr>{active==='Designs'?<><th>Design</th><th>Beam</th><th>Shade</th><th>Size</th><th>Threads</th></>:<th>Name</th>}<th>Action</th></tr></thead><tbody>{active==='Designs'?(filtered as Design[]).map(d=><tr key={d.id}><td><b>{d.name}</b></td><td>{d.beam}</td><td>{d.shade}</td><td>{d.size}</td><td>{d.threads.join(', ')||'—'}</td><td><button className="iconbtn"><Pencil size={16}/></button></td></tr>):(filtered as string[]).map(x=><tr key={x}><td>{x}</td><td><button className="iconbtn"><Pencil size={16}/></button></td></tr>)}</tbody></table></div></>}
function LoomProgram(){const[design]=useState(seedDesigns[0]);const[articles,setArticles]=useState(250);return <><Title title="Create Loom Program" subtitle="Prepare a clear program for any loom from 1 to 52"/><div className="panel form"><div className="formgrid"><Field label="Loom Number"><select>{Array.from({length:52},(_,i)=><option key={i+1}>{i+1}</option>)}</select></Field><Field label="Party Name"><select>{seed.Parties.map(x=><option>{x}</option>)}</select></Field><Field label="PO Number"><input placeholder="Enter PO number"/></Field><Field label="PO Date"><input type="date"/></Field><Field label="Production Date"><input type="date"/></Field><Field label="Design Number"><select><option>{design.name}</option></select></Field><Field label="Beam"><select><option>{design.beam}</option></select></Field><Field label="Shade"><select><option>{design.shade}</option></select></Field><Field label="Size"><select><option>{design.size}</option></select></Field><Field label="Pick"><input type="number" placeholder="Enter pick"/></Field><Field label="Meters"><input type="number" placeholder="Enter meters"/></Field><Field label="Articles to Produce"><input type="number" value={articles} onChange={e=>setArticles(Number(e.target.value))}/></Field></div><div className="threadbox"><label>Threads loaded automatically</label><div>{design.threads.map(t=><span key={t}>{t}</span>)}</div></div><div className="lshape"><div>{articles}</div></div><div className="formactions"><button>Save Draft</button><button>Print Preview</button><button className="primary">Save Loom Program</button></div></div></>}
function Field({label,children}:{label:string;children:any}){return <label className="field"><span>{label}</span>{children}</label>}
function HistoryPage(){const rows:Program[]=[{id:1,loom:12,party:'ABC Furnishings',po:'PO-2401',poDate:'2026-08-01',productionDate:'2026-08-06',design:'D-101',beam:'Beam 01',shade:'Ivory',threads:['Warp White'],pick:64,meters:840,articles:250}];return <><Title title="Production History" subtitle="Search, filter and export every loom record" action={<button><FileDown size={17}/>Export</button>}/><div className="panel"><div className="tabletools"><div className="search"><Search size={17}/><input placeholder="Search party, PO, loom or design..."/></div><button>Filters <ChevronDown size={16}/></button></div><table><thead><tr><th>Production Date</th><th>Loom</th><th>Party</th><th>PO</th><th>Design</th><th>Meters</th><th>Articles</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.productionDate}</td><td><b>Loom {r.loom}</b></td><td>{r.party}</td><td>{r.po}</td><td>{r.design}</td><td>{r.meters}</td><td>{r.articles}</td></tr>)}</tbody></table></div></>}
function Analytics(){return <><Title title="Analytics" subtitle="Daily, weekly and monthly production performance"/><div className="cards"><div className="card"><span>Daily Efficiency</span><strong>86.4%</strong><small>Across 52 looms</small></div><div className="card"><span>Weekly Meters</span><strong>8,942</strong><small>+6.2% vs last week</small></div><div className="card"><span>Monthly Articles</span><strong>10,486</strong><small>72% of target</small></div></div><div className="panel emptychart">Charts will populate automatically when production data is entered.</div></>}
function Placeholder({title}:{title:string}){return <><Title title={title} subtitle="This section is included in the ERP navigation"/><div className="panel emptychart">Ready for database connection and workflow completion.</div></>}
export default function App(){return <Shell/>}
